- cncfci.yml
QA https://github.com/crosscloudci/crosscloudci/issues/102
project:
logo_url: "https://raw.githubusercontent.com/cncf/artwork/bcabeb288a5c934278acd20b479ab8da494f2711/fluentd/icon/color/fluentd-icon-color.png"
display_name: Fluentd
sub_title: Logging
project_url: "https://github.com/fluent/fluentd"
> #102 QA Add accurate content to cncfci.yml

- cncfci.yml
- changing where project details are added to support external contributions
- merge from dev to staging for QA
> #102 QA Add .cncfci.yml for Fluentd on staging 

- cncfci.yml
Changes made: 
display_name: Fluentd2
sub_title: Logging2
project_url: "https://github.com/fluent/fluentd/releases"
> #102 QA fluentd config on staging

- .gitlab-ci.yml
- cncfci.yml
This request is needed for https://github.com/crosscloudci/ci_status_repository/pull/18
> Add support for separate environments for status results - K8s drop-down selection

- .gitlab-ci.yml
- LICENSE
- README.md
* changing where project details are added to support external contributions
> #102 Add .cncfci.yml for Fluentd on Production

- cncfci.yml
crosscloudci/crosscloudci#103 Stable/Release Ref
> crosscloudci/crosscloudci#103 Stable/Release Ref

- cncfci.yml
enable Fluentd v1.6.0
- released 7 days ago
> enable Fluentd v1.6.0

- cncfci.yml
> Enable Fluentd v1.6.0 on staging

- .gitlab-ci.yml
Add stable_ref and head_ref to integration
https://github.com/crosscloudci/crosscloudci/issues/103
- works as expected on prod, update integration branch
> Add stable_ref and head_ref to integration

- cncfci.yml
> enable fluentd v1.6.2 to staging

- cncfci.yml
- enable Fluentd v1.6.3 
- release 2 days ago
> enable Fluentd v1.6.3 on dev

- cncfci.yml
- enable Fluentd v1.6.3
- build status works as expected on dev
> enable Fluentd v1.6.3 on staging

- cncfci.yml
- enable Fluentd v1.6.3
- build status works as expected on staging
> enable Fluentd v1.6.3 on cncf.ci

- cncfci.yml
enable Fluentd v1.7.2 
- released on Sept 19
> enable Fluentd v1.7.2 on dev

- .gitlab-ci.yml
- cncfci.yml
enable Fluentd v1.7.2
- released on Sept 19
- build worked as expected on dev
> enable Fluentd v1.7.2 on staging

- cncfci.yml
enable Fluentd v1.7.2
- build worked as expected on staging
> enable Fluentd v1.7.2 on cncf.ci

- cncfci.yml
enable Fluentd v1.7.3
- released 3 days ago
> enable Fluentd v1.7.3 on dev

- cncfci.yml
> enable Fluentd v1.7.3 on staging

- .gitlab-ci.yml
Promote fix for fluentd builds to staging.
> Promote fix for fluentd builds to staging

- .gitlab-ci.yml
- cncfci.yml
Promote fix for fluentd builds to staging.
> Promote fix for fluentd builds to production.

- cncfci.yml
enable Fluentd v.1.7.4
- released on Oct 25
> enable Fluentd v.1.7.4 on dev

- cncfci.yml
1.9.2 was release on 02-12-2020
> Update stable to v1.9.2 on dev

- cncfci.yml
- v1.9.3 was released on 03-06-2020
> Update Stable to v1.9.3 on dev

- cncfci.yml
v1.10.1 was release on 04-02-2020
> Update Stable to v1.10.1 on dev

- .gitlab-ci.yml
- cncfci.yml
1. Fixes builds for Fluentd.
2. Bumps version to the latest stable.
Issues:
- vulk/cncf_ci#329
- vulk/cncf_ci#351
> PR to promote Fluentd fixes to production. vulk/cncf_ci#329 vulk/cncf_ci#351

- .gitlab-ci.yml
- cncfci.yml
- v1.10.1 was released on 04-02-2020
- update stable on staging
How Has This Been Tested?
---
Types of changes:
---
Checklist:
---
> Enable v1.10.1 on staging

- cncfci.yml
v1.10.2 was released on 04-14-2020
> Update Stable to v1.10.2 on dev

- cncfci.yml
v1.10.3 was released on 05-01-2020
> Update Stable to v1.10.3 on dev

- cncfci.yml
- v1.10.4 was release on 05/12/2020
> Update Stable to v1.10.4 on dev

- cncfci.yml
- v1.11.0 was released on 06/04/2020
> Update Stable to v1.11.0 on dev

- .gitlab-ci.yml
- cncfci.yml
This has already been pushed through but was never PR into integration so dev.cncf.ci reflects latest version.
> Merge Master v1.11.0 into Integration

- cncfci.yml
- v1.11.1 was released on 06/22/2020
> Update Stable to v1.11.1 on dev

- cncfci.yml
- v1.11.1 was released on 06/22/2020
- update stable on integration
- passing in cidev: https://gitlab.cidev.cncf.ci/fluent/fluentd/-/jobs/190858
> Update fluentd v1.11.1 on integration

- .gitlab-ci.yml
- cncfci.yml
Build passed as expected on staging: https://gitlab.staging.cncf.ci/fluent/fluentd/-/jobs/197155
- v1.11.1 was released on 06/22/2020
- update stable on production
How Has This Been Tested?
---
Types of changes:
---
Checklist:
---
> fluentd stable release v1.11.1 to production

- cncfci.yml
- v1.11.2 was released on 08-04-2020
> Update Stable to v1.11.2 on dev

- cncfci.yml
- v1.11.2 was released on 08-04-2020
- update stable on staging
- Passed trigger build: https://gitlab.dev.cncf.ci/fluent/fluentd/-/jobs/201864
> Update Stable to v1.11.2 on staging

- cncfci.yml
- v1.11.2 was released on 08-04-2020
- update stable on prod
- Passed trigger build on staging: https://gitlab.staging.cncf.ci/fluent/fluentd/-/jobs/198732
> Update Stable to v1.11.2 on Prod

- cncfci.yml
- v1.11.3 was release on 09/30/2020
> Update Stable to v1.11.3 on dev

- cncfci.yml
Passes Manual Pipeline on dev.cncf.ci: https://gitlab.dev.cncf.ci/fluent/fluentd/pipelines/50170
- v1.11.3 was release on 09/30/2020
- update stable on integration for dev.cncf.ci
> Update fluentd stable to v1.11.3 on integration (dev.cncf.ci)

- cncfci.yml
- v1.11.3 was release on 09/30/2020
- update stable on production
> Update fluentd stable to v1.11.3 on production

- cncfci.yml
- v1.11.4 was release on 10-13-2020
> Update Stable to v1.11.4 on dev

- cncfci.yml
- v1.11.4 was release on 10-13-2020
- update stable on integration for (dev.cncf.ci)
> Update Stable to v1.11.4 on integration (dev.cncf.ci)

- cncfci.yml
Need to merge commits into master, to avoid conflicts.
> Staging merge to fix commits into master

- .gitlab-ci.yml
- v1.11.4 was release on 10-13-2020
- update stable on production
> Update Stable to v1.11.4 on production

- cncfci.yml
- 1.11.5 was release on 11-6-2020
> Update Stable to v1.11.5 on dev

- cncfci.yml
- 1.6.7 was release on 01/04/2021
> Update Stable to v1.12.0 on dev

- cncfci.yml
- 1.6.7 was release on 01/04/2021
- passes manual pipeline test on dev: https://gitlab.dev.cncf.ci/fluent/fluentd/pipelines/50756
> Update Stable to v1.12.0 on dev (integration)

- cncfci.yml
- 1.6.7 was release on 01/04/2021
- passes manual pipeline test on dev: https://gitlab.dev.cncf.ci/fluent/fluentd/pipelines/50756
> Update Stable to v1.12.0 on staging

- cncfci.yml
- 1.6.7 was release on 01/04/2021
- update stable on production
- passes manual pipeline test on dev and staging: https://gitlab.dev.cncf.ci/fluent/fluentd/pipelines/50756 & https://gitlab.staging.cncf.ci/fluent/fluentd/-/jobs/202464
> Update fluentd stable to v1.12.0 on production

- .gitlab-ci.yml
https://github.com/crosscloudci/crosscloudci/issues/233
> Defaults to production #233

- cncfci.yml
- v1.12.1 was release on 02/18/2021
> Update Stable to v1.12.1 on dev

- .gitlab-ci.yml
- v1.12.1 was release on 02/18/2021
- update stable on prod
> Update fluentd stable to v1.12.1 on prod

- cncfci.yml
- v1.12.2 was release on 03/28/2021
> Update Stable to v1.12.2 on dev

- .gitlab-ci.yml
- v1.12.2 was release on 03/28/2021
- update stable on prod
> Update fluentd stable to v1.12.2 on prod
